---
title: A Failure of Self-Learning
output: html_notebook
---
```{r}
library(RSSL)
library(ggplot2)
require(gridExtra)
```
```{r}
set.seed(1)
# Set the datasets and corresponding formula objects
datasets <- list("2 Gaussian Expected"=generate2ClassGaussian(n=2000,d=2, var = 1,expected=TRUE),
    "2 Gaussian Non-Expected"=generate2ClassGaussian(n=2000,d=2, var = 1,expected=FALSE))
formulae <- list("2 Gaussian Expected"=formula(Class~.),
    "2 Gaussian Non-Expected"=formula(Class~.))
```
```{r}
# Figura 1
gp1<-ggplot(datasets[[1]],aes(x=X1,y=X2,color=Class)) + geom_point() + coord_equal()
gp2<-ggplot(datasets[[2]],aes(x=X1,y=X2,color=Class)) + geom_point() + coord_equal()
grid.arrange(gp1, gp2, ncol=2) # para subplots
```
```{r}
# Define the classifiers to be used
classifiers <- list("Supervised" = function(X,y,X_u,y_u) {LeastSquaresClassifier(X,y)},
    "Self-learning" = function(X,y,X_u,y_u) { SelfLearning(X,y,X_u,method = LeastSquaresClassifier)})
```
```{r}
# Define the performance measures to be used and run experiment
rep = 100
n_sizes = 10
measures <- list("Error" = measure_error, "Loss" = measure_losstest)
results_lc <- LearningCurveSSL(formulae,datasets,
    classifiers=classifiers,measures=measures,verbose=FALSE,
    repeats=rep,n_l=10,sizes = 2^(1:n_sizes))
```
```{r}
# Una muestra de cómo es la estructura de results_lc y cómo acceder a sus partes
str(results_lc)
results_lc[[2]]
results_lc[[2]]$`Number of unlabeled objects`[1:results_lc[[1]]]
```
```{r}
# Medias de errores en expected
df <- results_lc[[2]]

error_s_exp <- array(dim=c(rep,n_sizes))
for(r in 1:rep) {
    error_s_exp[r,] = df[df$repeats == r & df$Classifier == 'Supervised' & df$Measure == 'Error'
         & df$Dataset == '2 Gaussian Expected', "value"]
}
error_s_exp_mean <- apply(error_s_exp, 2, mean, na.rm=TRUE)

error_sl_exp <- array(dim=c(rep,n_sizes))
for(r in 1:rep) {
    error_sl_exp[r,] = df[df$repeats == r & df$Classifier == 'Self-learning' & df$Measure == 'Error'
         & df$Dataset == '2 Gaussian Expected', "value"]
}
error_sl_exp_mean <- apply(error_sl_exp, 2, mean, na.rm=TRUE)
```
```{r}
# Medias de errores en non-expected
error_s_noexp <- array(dim=c(rep,n_sizes))
for(r in 1:rep) {
    error_s_noexp[r,] = df[df$repeats == r & df$Classifier == 'Supervised' & df$Measure == 'Error'
         & df$Dataset == '2 Gaussian Non-Expected', "value"]
}
error_s_noexp_mean <- apply(error_s_noexp, 2, mean, na.rm=TRUE)

error_sl_noexp <- array(dim=c(rep,n_sizes))
for(r in 1:rep) {
    error_sl_noexp[r,] = df[df$repeats == r & df$Classifier == 'Self-learning' & df$Measure == 'Error'
         & df$Dataset == '2 Gaussian Non-Expected', "value"]
}
error_sl_noexp_mean <- apply(error_sl_noexp, 2, mean, na.rm=TRUE)
```
```{r}
# Figura 2
par(mfrow=c(1,2), pty="s") # Para subplots cuadrados
xticks <- df$`Number of unlabeled objects`[1:results_lc[[1]]]

p1 <- plot(xticks, error_s_exp_mean, type="o", ylim=c(0, 0.25), log="x", xaxt="n", 
           xlab="num. unlabeled", ylab="Error rate", 
           pch = 21, col='blue', asp = 0.1)
lines(xticks, error_sl_exp_mean, type="o", pch = 21, col='red')
axis(1, at=xticks,labels=xticks)
title(main="2 Gaussian Expected")

p2 <- plot(xticks, error_s_noexp_mean, type="o", ylim=c(0, 0.25), log="x", xaxt="n",
           xlab="num. unlabeled", ylab="Error rate",
           pch = 21, col='blue', asp = 0.1)
lines(xticks, error_sl_noexp_mean, type="o", pch = 21, col='red')
axis(1, at=xticks,labels=xticks)
title(main="2 Gaussian non-Expected")
```


